---
abstract: 'an exporter with the features of Sub::Exporter but only core dependencies'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.014, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Exporter-Tiny
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Exporter::Shiny:
    file: lib/Exporter/Shiny.pm
    version: 0.035_01
  Exporter::Tiny:
    file: lib/Exporter/Tiny.pm
    version: 0.035_01
requires:
  perl: 5.006001
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Exporter-Tiny/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Exporter-Tiny
  homepage: https://metacpan.org/release/Exporter-Tiny
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-exporter-tiny
version: 0.035_01
